provider:
  name: google

google:
  project: cloud-project-493810

domainFilters:
  - ben.fhbgl.study

sources:
  - ingress
  - service
  - gateway-httproute

policy: sync

txtOwnerId: demo-gke-cluster

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: ben-external-dns-sa@cloud-project-493810.iam.gserviceaccount.com

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 50m
    memory: 64Mi
