apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: vault-tenant
  namespace: tenant-example
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "tenant-example"
          serviceAccountRef:
            name: default
            namespace: tenant-example
