apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tenant-weatherapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/bhuang02/hochschule-burgenland-bswe-ws2024-2at-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: weatherapp-cloudsql-connection
                  key: privateIpAddress
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: weatherapp-cloudsql-connection
                  key: dbName
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: weatherapp-cloudsql-connection
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: weatherapp-db-password
                  key: password
            - name: AVWX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weatherapp-config
                  key: avwx-api-key
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: tenant-weatherapp
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
