apiVersion: database.fhbgl.study/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: weatherapp-cloudsql
  namespace: tenant-weatherapp
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parameters:
    gcpProjectId: crypto-haven-498307-q3
    region: europe-west4
    vpcName: inenp-cluster-vpc
    dbUsername: weatherapp
    dbName: weatherapp
    storageGB: 10
    tier: db-f1-micro
    databaseVersion: POSTGRES_16
  writeConnectionSecretToRef:
    name: weatherapp-cloudsql-connection
