apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weatherapp-config
  namespace: tenant-weatherapp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-tenant
    kind: SecretStore
  target:
    name: weatherapp-config
  data:
    - secretKey: avwx-api-key
      remoteRef:
        key: tenants/weatherapp/config
        property: avwx-api-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weatherapp-db-password
  namespace: tenant-weatherapp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-tenant
    kind: SecretStore
  target:
    name: weatherapp-db-password
  data:
    - secretKey: password
      remoteRef:
        key: tenants/weatherapp/cloudsql
        property: db-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
  namespace: tenant-weatherapp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-tenant
    kind: SecretStore
  target:
    name: ghcr-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: tenants/weatherapp/github
        property: dockerconfigjson-raw
