---
# yamllint disable rule:line-length
apiVersion: platform.fhbgl.study/v1alpha1
kind: XTenant
metadata:
  name: weatherapp
spec:
  parameters:
    name: weatherapp
    namespace: tenant-weatherapp
    hostname: weather.crypto-haven.fhbgl.study
    vaultPath: tenants/weatherapp
    vaultRole: weatherapp-tenant
    backendImage: ghcr.io/bhuang02/hochschule-burgenland-bswe-ws2024-2at-backend:latest
    frontendImage: ghcr.io/bhuang02/frontend:latest
    gcpProjectId: crypto-haven-498307-q3
    region: europe-west4
    vpcName: inenp-cluster-vpc
    dbUsername: weatherapp
    dbName: weatherapp
    storageGB: 10
    tier: db-f1-micro
    databaseVersion: POSTGRES_16
