---
# Root password for the Cloud SQL postgres superuser
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weatherapp-root-password
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: weatherapp-cloudsql-root-password
  data:
    - secretKey: password
      remoteRef:
        key: tenants/weatherapp/cloudsql
        property: root-password
---
# Password for the weatherapp DB user
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weatherapp-db-password
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: weatherapp-cloudsql-db-password
  data:
    - secretKey: password
      remoteRef:
        key: tenants/weatherapp/cloudsql
        property: db-password
---
# Root password for the staging Cloud SQL postgres superuser
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weatherapp-staging-root-password
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: weatherapp-staging-cloudsql-root-password
  data:
    - secretKey: password
      remoteRef:
        key: tenants/weatherapp-staging/cloudsql
        property: root-password
---
# Password for the staging weatherapp DB user
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weatherapp-staging-db-password
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: weatherapp-staging-cloudsql-db-password
  data:
    - secretKey: password
      remoteRef:
        key: tenants/weatherapp-staging/cloudsql
        property: db-password
