---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - providers.yaml
  - provider-config.yaml
  - deployment-runtime-config.yaml
  - compositions
  - xrds
  - function-patch-transform.yaml
  - cloudsql-secrets.yaml
