apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-ben-fhbgl-study
  namespace: gateway-system
spec:
  secretName: wildcard-ben-fhbgl-study-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.ben.fhbgl.study"
    - "ben.fhbgl.study"
