apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-crypto-haven-fhbgl-study
  namespace: gateway-system
spec:
  secretName: wildcard-crypto-haven-fhbgl-study-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.crypto-haven.fhbgl.study"
    - "crypto-haven.fhbgl.study"
