---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xappidentities.iam.fhbgl.study
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  group: iam.fhbgl.study
  names:
    kind: XAppIdentity
    plural: xappidentities
  claimNames:
    kind: AppIdentity
    plural: appidentities
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - parameters
              properties:
                parameters:
                  type: object
                  required:
                    - tenantName
                    - namespace
                    - projectID
                    - iamRole
                  properties:
                    tenantName:
                      type: string
                    namespace:
                      type: string
                    projectID:
                      type: string
                    iamRole:
                      type: string