apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: infra
  source:
    repoURL: https://github.com/Toerbi1/gitops-gke.git
    targetRevision: HEAD
    path: infra/external-secrets/config
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
