---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp2
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tenants
  source:
    repoURL: https://github.com/Toerbi1/gitops-gke.git
    targetRevision: test/e2e-integration
    path: tenants/testapp2
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-testapp2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true